# Generated by Django 5.1.6 on 2025-03-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='Network',
            new_name='network',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Release_date',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='Title',
            new_name='title',
        ),
    ]
