# Generated by Django 5.1.6 on 2025-03-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_rest_app', '0002_rename_network_show_network_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='image_link',
            field=models.URLField(default='https://google.com'),
            preserve_default=False,
        ),
    ]
